
#include "items.h"
#include <vector>
#include "inventorychanger.h"
#include "../../SDK/Utils/Enums.hpp"
#include <map>
const std::vector<std::pair<int, const char*>> save_guns =
{
{ WEAPON_AK47,		"AK-47" },
{ WEAPON_AUG,			"AUG" },
{ WEAPON_AWP,			"AWP" },
{ WEAPON_CZ75A,		"CZ75-A" },
{ WEAPON_DEAGLE,		"Desert Eagle" },
{ WEAPON_ELITE,		"Dual Barettas" },
{ WEAPON_FAMAS,		"Famas" },
{ WEAPON_FIVESEVEN, 	"Five-Seven" },
{ WEAPON_GALILAR,		"Galil-AR" },
{ WEAPON_G3SG1,		"G3SG1" },
{ WEAPON_GLOCK,		"Glock-18" },
{ WEAPON_M249,		"M249" },
{ WEAPON_M4A1_SILENCER,       "M4A1-S" },
{ WEAPON_M4A1,		"M4A4" },
{ WEAPON_MAC10,		"MAC-10" },
{ WEAPON_MAG7,		"Mag-7" },
{ WEAPON_MP7,			"MP7" },
{ WEAPON_MP5SD,		"MP5-SD"},
{ WEAPON_MP9,			"MP9" },
{ WEAPON_NEGEV,		"Negev" },
{ WEAPON_NOVA,		"Nova" },
{ WEAPON_HKP2000,		"P2000" },
{ WEAPON_P250,		"P250" },
{ WEAPON_P90,			"P90" },
{ WEAPON_BIZON,		"PP-Bizon" },
{ WEAPON_REVOLVER,	"R8 Revolver" },
{ WEAPON_SAWEDOFF,	"Sawed-Off" },
{ WEAPON_SCAR20,		"SCAR-20" },
{ WEAPON_SG553,		"SG-556" },
{ WEAPON_SSG08,		"Scout" },
{ WEAPON_TEC9,		"Tec-9" },
{ WEAPON_UMP45,		"UMP-45" },
{ WEAPON_USP_SILENCER,	    "USP-S" },
{ WEAPON_XM1014,      "XM1014" },
};
const std::map<short, weapon_infos> k_weapon_info = {
	{ WEAPON_KNIFE, { "models/weapons/v_knife_default_ct.mdl", "knife" } },
	{ WEAPON_KNIFE_T, { "models/weapons/v_knife_default_t.mdl", "knife_t" } },
	{ WEAPON_KNIFE_BAYONET, { "models/weapons/v_knife_bayonet.mdl", "bayonet" } },
	{ WEAPON_KNIFE_FLIP, { "models/weapons/v_knife_flip.mdl", "knife_flip" } },
	{ WEAPON_KNIFE_GUT, { "models/weapons/v_knife_gut.mdl", "knife_gut" } },
	{ WEAPON_KNIFE_KARAMBIT, { "models/weapons/v_knife_karam.mdl", "knife_karambit" } },
	{ WEAPON_KNIFE_M9_BAYONET, { "models/weapons/v_knife_m9_bay.mdl", "knife_m9_bayonet" } },
	{ WEAPON_KNIFE_TACTICAL, { "models/weapons/v_knife_tactical.mdl", "knife_tactical" } },
	{ WEAPON_KNIFE_FALCHION, { "models/weapons/v_knife_falchion_advanced.mdl", "knife_falchion" } },
	{ WEAPON_KNIFE_SURVIVAL_BOWIE, { "models/weapons/v_knife_survival_bowie.mdl", "knife_survival_bowie" } },
	{ WEAPON_KNIFE_BUTTERFLY, { "models/weapons/v_knife_butterfly.mdl", "knife_butterfly" } },
	{ WEAPON_KNIFE_PUSH, { "models/weapons/v_knife_push.mdl", "knife_push" } },
	{ WEAPON_KNIFE_URSUS, { "models/weapons/v_knife_ursus.mdl", "knife_ursus" } },
	{ WEAPON_KNIFE_GYPSY_JACKKNIFE, { "models/weapons/v_knife_gypsy_jackknife.mdl", "knife_gypsy_jackknife" } },
	{ WEAPON_KNIFE_STILETTO, { "models/weapons/v_knife_stiletto.mdl", "knife_stiletto" } },
	{ WEAPON_KNIFE_WIDOWMAKER, { "models/weapons/v_knife_widowmaker.mdl", "knife_widowmaker" } },
	{ WEAPON_KNIFE_SKELETON,{"models/weapons/v_knife_skeleton.mdl","knife_skeleton" }},
	{ WEAPON_KNIFE_OUTDOOR,{"models/weapons/v_knife_outdoor.mdl","knife_outdoor"}},
	{ WEAPON_KNIFE_CANIS,{"models/weapons/v_knife_canis.mdl","knife_canis"}},
	{ WEAPON_KNIFE_CORD,{"models/weapons/v_knife_cord.mdl","knife_cord"}},
	{ WEAPON_KNIFE_CSS,{"models/weapons/v_knife_css.mdl","knife_css"}},
	{ GLOVE_T_SIDE,{ "models/weapons/v_models/arms/glove_fingerless/v_glove_fingerless.mdl" } },
	{ GLOVE_STUDDED_BLOODHOUND,{ "models/weapons/v_models/arms/glove_bloodhound/v_glove_bloodhound.mdl", "studded_bloodhound_gloves" } },
	{ GLOVE_CT_SIDE,{ "models/weapons/v_models/arms/glove_hardknuckle/v_glove_hardknuckle.mdl" } },
	{ GLOVE_SPORTY,{ "models/weapons/v_models/arms/glove_sporty/v_glove_sporty.mdl", "sporty_gloves" } },
	{ GLOVE_SLICK,{ "models/weapons/v_models/arms/glove_slick/v_glove_slick.mdl", "slick_gloves"} },
	{ GLOVE_LEATHER_WRAP,{ "models/weapons/v_models/arms/glove_handwrap_leathery/v_glove_handwrap_leathery.mdl", "leather_handwraps" } },
	{ GLOVE_MOTORCYCLE,{ "models/weapons/v_models/arms/glove_motorcycle/v_glove_motorcycle.mdl", "motorcycle_gloves" } },
	{ GLOVE_SPECIALIST,{ "models/weapons/v_models/arms/glove_specialist/v_glove_specialist.mdl", "specialist_gloves" } },
	{ GLOVE_HYDRA,{ "models/weapons/v_models/arms/glove_bloodhound/v_glove_bloodhound_hydra.mdl", "studded_hydra_gloves" } },
	//{ GLOVE_BROKENFRAG,{ "models/weapons/v_models/arms/glove_bloodhound/v_glove_bloodhound_brokenfang.mdl", "studded_brokenfang_gloves" } },
	{5105, {"models/player/custom_player/legacy/tm_leet_variantg.mdl", "knife"}},
	{5106, {"models/player/custom_player/legacy/tm_leet_varianth.mdl", "knife"}},
	{5107, {"models/player/custom_player/legacy/tm_leet_varianti.mdl", "knife"}},
	{5108, {"models/player/custom_player/legacy/tm_leet_variantf.mdl", "knife"}},
	{5205, {"models/player/custom_player/legacy/tm_phoenix_varianth.mdl", "knife"}},
	{5206, {"models/player/custom_player/legacy/tm_phoenix_variantf.mdl", "knife"}},
	{5207, {"models/player/custom_player/legacy/tm_phoenix_variantg.mdl", "knife"}},
	{5208, {"models/player/custom_player/legacy/tm_phoenix_varianti.mdl", "knife"}},
	{5305, {"models/player/custom_player/legacy/ctm_fbi_variantf.mdl", "knife"}},
	{5306, {"models/player/custom_player/legacy/ctm_fbi_variantg.mdl", "knife"}},
	{5307, {"models/player/custom_player/legacy/ctm_fbi_varianth.mdl", "knife"}},
	{5308, {"models/player/custom_player/legacy/ctm_fbi_variantb.mdl", "knife"}},
	{5400, {"models/player/custom_player/legacy/ctm_st6_variantk.mdl", "knife"}},
	{5401, {"models/player/custom_player/legacy/ctm_st6_variante.mdl", "knife"}},
	{5402, {"models/player/custom_player/legacy/ctm_st6_variantg.mdl", "knife"}},
	{5403, {"models/player/custom_player/legacy/ctm_st6_variantm.mdl", "knife"}},
	{5404, {"models/player/custom_player/legacy/ctm_st6_varianti.mdl", "knife"}},
	{4619, {"models/player/custom_player/legacy/ctm_st6_variantj.mdl", "knife"}},
	{4680, {"models/player/custom_player/legacy/ctm_st6_variantl.mdl", "knife"}},
	{5500, {"models/player/custom_player/legacy/tm_balkan_variantf.mdl", "knife"}},
	{5501, {"models/player/custom_player/legacy/tm_balkan_varianti.mdl", "knife"}},
	{5502, {"models/player/custom_player/legacy/tm_balkan_variantg.mdl", "knife"}},
	{5503, {"models/player/custom_player/legacy/tm_balkan_variantj.mdl", "knife"}},
	{5504, {"models/player/custom_player/legacy/tm_balkan_varianth.mdl", "knife"}},
	{4718, {"models/player/custom_player/legacy/tm_balkan_variantk.mdl", "knife"}},
	{5505, {"models/player/custom_player/legacy/tm_balkan_variantl.mdl", "knife"}},
	{5601, {"models/player/custom_player/legacy/ctm_sas_variantf.mdl", "knife"}},
	{4711, {"models/player/custom_player/legacy/ctm_swat_variante.mdl", "knife"}},
	{4712, {"models/player/custom_player/legacy/ctm_swat_variantf.mdl", "knife"}},
	{4713, {"models/player/custom_player/legacy/ctm_swat_variantg.mdl", "knife"}},
	{4714, {"models/player/custom_player/legacy/ctm_swat_varianth.mdl", "knife"}},
	{4715, {"models/player/custom_player/legacy/ctm_swat_varianti.mdl", "knife"}},
	{4716, {"models/player/custom_player/legacy/ctm_swat_variantj.mdl", "knife"}},
	{4726, {"models/player/custom_player/legacy/tm_professional_varf.mdl", "knife"}},
	{4733, {"models/player/custom_player/legacy/tm_professional_varf1.mdl", "knife"}},
	{4734, {"models/player/custom_player/legacy/tm_professional_varf2.mdl", "knife"}},
	{4735, {"models/player/custom_player/legacy/tm_professional_varf3.mdl", "knife"}},
	{4736, {"models/player/custom_player/legacy/tm_professional_varf4.mdl", "knife"}},
	{4727, {"models/player/custom_player/legacy/tm_professional_varg.mdl", "knife"}},
	{4728, {"models/player/custom_player/legacy/tm_professional_varh.mdl", "knife"}},
	{4732, {"models/player/custom_player/legacy/tm_professional_vari.mdl", "knife"}},
	{4730, {"models/player/custom_player/legacy/tm_professional_varj.mdl", "knife"}},
};

const std::map<short, const char*> k_glove_names = {
	{WEAPON_NONE, "Default"},
	{GLOVE_STUDDED_BLOODHOUND, "Bloodhound"},
	{GLOVE_SPORTY, "Sporty"},
	{GLOVE_SLICK, "Slick"},
	{GLOVE_LEATHER_WRAP, "Handwrap"},
	{GLOVE_MOTORCYCLE, "Motorcycle"},
	{GLOVE_SPECIALIST, "Specialist"},
	{GLOVE_HYDRA, "Hydra"}
};

const std::map<short, const char*> k_knife_names = {
	{WEAPON_NONE, "Default"},
	{WEAPON_KNIFE_BAYONET, "Bayonet"},
	{WEAPON_KNIFE_FLIP, "Flip Knife"},
	{WEAPON_KNIFE_GUT, "Gut Knife"},
	{WEAPON_KNIFE_KARAMBIT, "Karambit"},
	{WEAPON_KNIFE_M9_BAYONET, "M9 Bayonet"},
	{WEAPON_KNIFE_TACTICAL, "Huntsman Knife"},
	{WEAPON_KNIFE_FALCHION, "Falchion Knife"},
	{WEAPON_KNIFE_SURVIVAL_BOWIE, "Bowie Knife"},
	{WEAPON_KNIFE_BUTTERFLY, "Butterfly Knife"},
	{WEAPON_KNIFE_PUSH, "Shadow Daggers"},
	{WEAPON_KNIFE_URSUS, "Ursus Knife"},
	{WEAPON_KNIFE_GYPSY_JACKKNIFE, "Navaja Knife"},
	{WEAPON_KNIFE_STILETTO, "Stiletto Knife"},
	{WEAPON_KNIFE_WIDOWMAKER, "Talon Knife"},
	{WEAPON_KNIFE_SKELETON,"Skeleton Knife"},
	{WEAPON_KNIFE_OUTDOOR,"Nomad Knife"},
	{WEAPON_KNIFE_CANIS,"Survival Knife"},
	{WEAPON_KNIFE_CORD,"Paracord Knife"},
	{WEAPON_KNIFE_CSS,"Classic Knife"},
};

const std::map<short, const char*> k_item_names = {
	{WEAPON_CZ75A, "CZ75 Auto"},
	{WEAPON_DEAGLE, "Desert Eagle"},
	{WEAPON_ELITE, "Dual Berettas"},
	{WEAPON_FIVESEVEN, "Five-SeveN"},
	{WEAPON_HKP2000, "P2000"},
	{WEAPON_P250, "P250"},
	{WEAPON_USP_SILENCER, "USP-S"},
	{WEAPON_TEC9, "Tec-9"},
	{WEAPON_REVOLVER, "R8 Revolver"},
	{WEAPON_GLOCK, "Glock-18"},

	{WEAPON_MAG7, "MAG-7"},
	{WEAPON_NOVA, "Nova"},
	{WEAPON_SAWEDOFF, "Sawed-Off"},
	{WEAPON_XM1014, "XM1014"},

	{WEAPON_UMP45, "UMP-45"},
	{WEAPON_P90, "P90"},
	{WEAPON_BIZON, "PP-Bizon"},
	{WEAPON_MAC10, "MAC-10"},
	{WEAPON_MP7, "MP7"},
	{WEAPON_MP9, "MP9"},
	{WEAPON_MP5SD, "MP5-SD"},

	{WEAPON_M249, "M249"},
	{WEAPON_NEGEV, "Negev"},

	{WEAPON_AK47, "AK-47"},
	{WEAPON_AUG, "AUG"},
	{WEAPON_GALILAR, "Galil AR"},
	{WEAPON_M4A1_SILENCER, "M4A1-S"},
	{WEAPON_M4A1, "M4A4"},
	{WEAPON_SG553, "SG 553"},
	{WEAPON_FAMAS, "FAMAS"},

	{WEAPON_AWP, "AWP"},
	{WEAPON_G3SG1, "G3SG1"},
	{WEAPON_SCAR20, "SCAR-20"},
	{WEAPON_SSG08, "SSG 08"},

	{WEAPON_KNIFE, "Knife"},
	{WEAPON_KNIFE_T, "Knife"},
	{WEAPON_KNIFEGG, "Knife"},
	{WEAPON_KNIFE_GHOST, "Knife"},
	{WEAPON_KNIFE_BAYONET, "Knife"},
	{WEAPON_KNIFE_FLIP, "Knife"},
	{WEAPON_KNIFE_GUT, "Knife"},
	{WEAPON_KNIFE_KARAMBIT, "Knife"},
	{WEAPON_KNIFE_M9_BAYONET, "Knife"},
	{WEAPON_KNIFE_TACTICAL, "Knife"},
	{WEAPON_KNIFE_FALCHION, "Knife"},
	{WEAPON_KNIFE_SURVIVAL_BOWIE, "Knife"},
	{WEAPON_KNIFE_BUTTERFLY, "Knife"},
	{WEAPON_KNIFE_PUSH, "Knife"},
	{WEAPON_KNIFE_URSUS, "Knife"},
	{WEAPON_KNIFE_GYPSY_JACKKNIFE, "Knife"},
	{WEAPON_KNIFE_STILETTO, "Knife"},
	{WEAPON_KNIFE_WIDOWMAKER, "Knife"},
	{WEAPON_KNIFE_SKELETON,"Knife"},
	{WEAPON_KNIFE_OUTDOOR,"Knife"},
	{WEAPON_KNIFE_CANIS,"Knife"},
	{WEAPON_KNIFE_CORD,"Knife"},
	{WEAPON_KNIFE_CSS,"Knife"},

	{WEAPON_TASER, "Zeus x27"},

	{WEAPON_HEGRENADE, "HE Grenade"},
	{WEAPON_SMOKEGRENADE, "Smoke Grenade"},
	{WEAPON_FLASHBANG, "Flashbang"},
	{WEAPON_MOLOTOV, "Molotov"},
	{WEAPON_INCGRENADE, "Incendiary Grenade"},
	{WEAPON_DECOY, "Decoy"},

	{WEAPON_C4, "C4"},

	{WEAPON_HEALTHSHOT, "Health Shot"},

	{WEAPON_SNOWBALL, "Snowball"},

	// DangerZone
	{WEAPON_FISTS, "Fists"},
	{WEAPON_BREACHCHARGE, "Breach Charge"},
	{WEAPON_TABLET, "Tablet"},
	{WEAPON_AXE, "Axe"},
	{WEAPON_HAMMER, "Hammer"},
	{WEAPON_SPANNER, "Spanner"},
	{WEAPON_FIREBOMB, "Fire Bomb"},
	{WEAPON_DIVERSION, "Diversion"},
	{WEAPON_FRAG_GRENADE, "Frag Grenade"},
	{WEAPON_BUMPMINE, "Bump Mine"},
	{WEAPON_SHIELD, "Shield"},
};

const std::vector<CWeaponSelectList> k_inventory_names = {
	{WEAPON_CZ75A, "weapon_cz75a", 0},
	{WEAPON_DEAGLE, "weapon_deagle", 0},
	{WEAPON_ELITE, "weapon_elite", 0},
	{WEAPON_FIVESEVEN, "weapon_fiveseven", 0},
	{WEAPON_HKP2000, "weapon_hkp2000", 0},
	{WEAPON_P250, "weapon_p250", 0},
	{WEAPON_USP_SILENCER, "weapon_usp_silencer", 0},
	{WEAPON_TEC9, "weapon_tec9", 0},
	{WEAPON_REVOLVER, "weapon_revolver", 0},
	{WEAPON_GLOCK, "weapon_glock", 0},

	{WEAPON_MAG7, "weapon_mag7", 0},
	{WEAPON_NOVA, "weapon_nova", 0},
	{WEAPON_SAWEDOFF, "weapon_sawedoff", 0},
	{WEAPON_XM1014, "weapon_xm1014", 0},

	{WEAPON_UMP45, "weapon_ump45", 0},
	{WEAPON_P90, "weapon_p90", 0},
	{WEAPON_BIZON, "weapon_bizon", 0},
	{WEAPON_MAC10, "weapon_mac10", 0},
	{WEAPON_MP7, "weapon_mp7", 0},
	{WEAPON_MP9, "weapon_mp9", 0},
	{WEAPON_MP5SD, "weapon_mp5sd", 0},

	{WEAPON_M249, "weapon_m249", 0},
	{WEAPON_NEGEV, "weapon_negev", 0},

	{WEAPON_AK47, "weapon_ak47", 0},
	{WEAPON_AUG, "weapon_aug", 0},
	{WEAPON_GALILAR, "weapon_galilar", 0},
	{WEAPON_M4A1_SILENCER, "weapon_m4a1_silencer", 0},
	{WEAPON_M4A1, "weapon_m4a1", 0},
	{WEAPON_SG553, "weapon_sg556", 0},
	{WEAPON_FAMAS, "weapon_famas", 0},

	{WEAPON_AWP, "weapon_awp", 0},
	{WEAPON_G3SG1, "weapon_g3sg1", 0},
	{WEAPON_SCAR20, "weapon_scar20", 0},
	{WEAPON_SSG08, "weapon_ssg08", 0},

	{WEAPON_KNIFE_BAYONET, "weapon_bayonet", 5},
	{WEAPON_KNIFE_FLIP, "weapon_knife_flip", 5},
	{WEAPON_KNIFE_GUT, "weapon_knife_gut", 5},
	{WEAPON_KNIFE_KARAMBIT, "weapon_knife_karambit", 5},
	{WEAPON_KNIFE_M9_BAYONET, "weapon_knife_m9_bayonet", 5},
	{WEAPON_KNIFE_TACTICAL, "weapon_knife_tactical", 5},
	{WEAPON_KNIFE_FALCHION, "weapon_knife_falchion", 5},
	{WEAPON_KNIFE_SURVIVAL_BOWIE, "weapon_knife_survival_bowie", 5},
	{WEAPON_KNIFE_BUTTERFLY, "weapon_knife_butterfly", 5},
	{WEAPON_KNIFE_PUSH, "weapon_knife_push", 5},
	{WEAPON_KNIFE_URSUS, "weapon_knife_ursus", 5},
	{WEAPON_KNIFE_GYPSY_JACKKNIFE, "weapon_knife_gypsy_jackknife", 5},
	{WEAPON_KNIFE_STILETTO, "weapon_knife_stiletto", 5},
	{WEAPON_KNIFE_WIDOWMAKER, "weapon_knife_widowmaker", 5},
	{WEAPON_KNIFE_SKELETON,"weapon_knife_skeleton", 5},
	{WEAPON_KNIFE_OUTDOOR,"weapon_knife_outdoor", 5},
	{WEAPON_KNIFE_CANIS,"weapon_knife_canis", 5},
	{WEAPON_KNIFE_CORD,"weapon_knife_cord", 5},
	{WEAPON_KNIFE_CSS,"weapon_knife_css", 5},

	{GLOVE_STUDDED_BLOODHOUND, "studded_bloodhound_gloves", 5},
	{GLOVE_SPORTY, "sporty_gloves", 5},
	{GLOVE_SLICK, "slick_gloves", 5},
	{GLOVE_LEATHER_WRAP, "leather_handwraps", 5},
	{GLOVE_MOTORCYCLE, "motorcycle_gloves", 5},
	{GLOVE_SPECIALIST, "specialist_gloves", 5},
	{GLOVE_HYDRA, "studded_hydra_gloves", 5},

	{5105, "customplayer_tm_leet_variantg", 2},
	{5106, "customplayer_tm_leet_varianth", 3},
	{5107, "customplayer_tm_leet_varianti", 4},
	{5108, "customplayer_tm_leet_variantf", 5},
	{5205, "customplayer_tm_phoenix_varianth", 2},
	{5206, "customplayer_tm_phoenix_variantf", 2},
	{5207, "customplayer_tm_phoenix_variantg", 3},
	{5208, "customplayer_tm_phoenix_varianti", 2},
	{5305, "customplayer_ctm_fbi_variantf", 2},
	{5306, "customplayer_ctm_fbi_variantg", 3},
	{5307, "customplayer_ctm_fbi_varianth", 4},
	{5308, "customplayer_ctm_fbi_variantb", 5},
	{5400, "customplayer_ctm_st6_variantk", 2},
	{5401, "customplayer_ctm_st6_variante", 2},
	{5402, "customplayer_ctm_st6_variantg", 3},
	{5403, "customplayer_ctm_st6_variantm", 4},
	{5404, "customplayer_ctm_st6_varianti", 5},
	{4619, "customplayer_ctm_st6_variantj", 4},
	{4680, "customplayer_ctm_st6_variantl", 4},
	{5500, "customplayer_tm_balkan_variantf", 3},
	{5501, "customplayer_tm_balkan_varianti", 3},
	{5502, "customplayer_tm_balkan_variantg", 2},
	{5503, "customplayer_tm_balkan_variantj", 2},
	{5504, "customplayer_tm_balkan_varianth", 5},
	{4718, "customplayer_tm_balkan_variantk", 4},
	{5505, "customplayer_tm_balkan_variantl", 2},
	{5601, "customplayer_ctm_sas_variantf", 2},
	{4711, "customplayer_ctm_swat_variante", 5},
	{4712, "customplayer_ctm_swat_variantf", 4},
	{4713, "customplayer_ctm_swat_variantg", 3},
	{4714, "customplayer_ctm_swat_varianth", 2},
	{4715, "customplayer_ctm_swat_varianti", 2},
	{4716, "customplayer_ctm_swat_variantj", 2},
	{4726, "customplayer_tm_professional_varf", 5},
	{4733, "customplayer_tm_professional_varf1", 5},
	{4734, "customplayer_tm_professional_varf2", 5},
	{4735, "customplayer_tm_professional_varf3", 5},
	{4736, "customplayer_tm_professional_varf4", 5},
	{4727, "customplayer_tm_professional_varg", 4},
	{4728, "customplayer_tm_professional_varh", 3},
	{4732, "customplayer_tm_professional_vari", 4},
	{4730, "customplayer_tm_professional_varj", 3},
};